server:
  port: 8081

spring:
  application:
    name: cqrs-banking-app
  config:
    import: optional:file:.env[.properties]

  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}/${POSTGRES_DB}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none

    liquibase:
    change-log: classpath:liquibase/db.changelog.yaml
    enabled: true

security:
  jwt:
    secret: ${JWT_SECRET}
    access-duration: ${JWT_ACCESS_DURATION}
    refresh-duration: ${JWT_REFRESH_DURATION}
